### ISSUE TITLE
[Talk Proposal] Fully secure GraphQL HTTP queries

### ISSUE THREAD

**Issue by koresar** [team-alembic/graphql-sydney#7]
Title: Fully secure GraphQL HTTP queries

Length: 20-30 min

Description: Do you develop for banks or other secure institution? Have you ever thought that your website communication to server can be easily reverse engineered? With modern web development tools you can fully secure your app communication with the server. This talk quickly explains how you can do that with little effort using HTTP and GraphQL.

About the speaker: Vasyl is a regular Ukrainian developer passioned in all things JavaScript, microservices, Web, and GraphQL.
https://twitter.com/kore_sar

**Comment by paulfioravanti** [comment]
Thanks for the talk, Vasyl! If you've shared your talk slides publicly anywhere, please tweet them at `@graphqlsydney` and we'll retweet them.
