### ISSUE TITLE
[Talk Proposal] Angular Graphql Magic

### ISSUE THREAD

**Issue by kuncevic** [team-alembic/graphql-sydney#9]
Title: Angular Graphql Magic
Length: 20-30

Description: Do you have graphql api that you want to consume in your Angular app? Do you want to learn how to generate services and typescirpt classes ready to be consumed within your Angular app? I will show the best practices how to integrate graphql in to your Angular app with 0 boilerplate. I will demonstrate how to generate all the code your Angular app needs to interact with existing graphql server.

Speaker: Aliaksei is a Sydney-based Angular expert. Aliaksei sharing his Angular expertise by consulting dev teams teaching Angular best practices as well as running Angular workshops. Sometimes you can see him presenting Angular-related topics on ngSydney meetup group. Also, Aliaksei is running Sydney-based meetup called Frontend Tech and Angular Minsk meetup based in Belarus. Ref: https://twitter.com/kuncevic

**Comment by paulfioravanti** [comment]
Hi Aliaksei, thanks very much for the talk submission! It would be great to lock you in for the February meetup. Just one thing, though: could you please re-file this issue on the GraphQL Sydney meetup repo, please? It’s at: https://github.com/graphqlsydney/graphqlsydney/issues

Then, we’ll lock you in for February!
